const constant = {
  COLOR_DOT_CORE: "black",
  COLOR_LESS_20: "rgb(66,255,246)",
  COLOR_LESS_40: "rgb(63,152,190)",
  COLOR_MORE_40: "rgb(50,82,119)",
  COLOR_TIME_LABEL: "rgb(7,32,40)",
  DOT_RADIUS: 6,
  DOT_STROKE_WIDTH: 4,
  DOT_DISAPPEAR_SECOND: 20,
  DOT_SPAN: 5,
  PATH_STROKE_WIDTH: 6,
  LABEL_PIN_HEIGHT: 15,
  LABEL_PIN_WIDTH: 2,
  LABEL_TEXT_LR_PADDING: 10,
  ACTIVE_TIME_SPAN: 10,
  DISPLAY_NONE: 0,
  DISPLAY_INACTIVE: 1,
  DISPLAY_INACTIVE_HOVER: 2,
  DISPLAY_ACTIVE: 3,
}

export default constant;